# Usa una imagen base de Node.js
FROM node:18

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias (package.json y package-lock.json)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Expone el puerto que Vite usa por defecto
EXPOSE 5173

# Comando para iniciar la aplicación de Vite en modo desarrollo
CMD ["npm", "run", "dev", "--", "--host"]
