-- Role: cinefans
-- DROP ROLE IF EXISTS cinefans;

CREATE ROLE cinefans WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  BYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:XCKm3AFNPbiZsw89Ki95sg==$ONg5sm2VdfkUETiLxToYlM4aUaOTnSXGu0Yaq7+tckw=:1tDU1YH/LFjX2cZndZK11p+Q11btQbM75pE6ES7DS00=';

GRANT postgres TO cinefans;